"""
app.py
Streamlit demo for the brain tumor MRI classifier.

Usage:
    streamlit run app/app.py
"""

import os
import sys

import numpy as np
import streamlit as st
from PIL import Image
from tensorflow import keras

sys.path.append(os.path.join(os.path.dirname(__file__), "..", "src"))
from data_loader import IMG_SIZE, CLASS_NAMES  # noqa: E402

MODEL_PATH = os.environ.get("MODEL_PATH", "models/best_model.h5")

st.set_page_config(page_title="Brain Tumor MRI Classifier", page_icon="🧠", layout="centered")

st.title("🧠 Brain Tumor Detection from MRI")
st.caption(
    "Educational demo — classifies an MRI scan as glioma, meningioma, "
    "pituitary tumor, or no tumor. **Not a medical device.**"
)


@st.cache_resource
def load_model(path):
    if not os.path.exists(path):
        return None
    return keras.models.load_model(path)


model = load_model(MODEL_PATH)

if model is None:
    st.warning(
        f"No trained model found at `{MODEL_PATH}`. "
        "Train one first with `python src/train.py`, then relaunch this app."
    )
else:
    uploaded_file = st.file_uploader("Upload an MRI image", type=["jpg", "jpeg", "png"])

    if uploaded_file is not None:
        image = Image.open(uploaded_file).convert("RGB")
        st.image(image, caption="Uploaded MRI scan", use_container_width=True)

        resized = image.resize(IMG_SIZE)
        arr = np.asarray(resized, dtype=np.float32) / 255.0
        arr = np.expand_dims(arr, axis=0)

        with st.spinner("Analyzing scan..."):
            probs = model.predict(arr, verbose=0)[0]

        idx = int(np.argmax(probs))
        label = CLASS_NAMES[idx]
        confidence = float(probs[idx])

        st.subheader(f"Prediction: `{label}`")
        st.metric("Confidence", f"{confidence:.1%}")

        st.write("Probability breakdown:")
        for cls, p in sorted(zip(CLASS_NAMES, probs), key=lambda kv: -kv[1]):
            st.progress(float(p), text=f"{cls}: {p:.1%}")

        st.info(
            "This prediction is generated by a machine learning model for "
            "educational purposes only and should not be used for medical "
            "diagnosis. Please consult a qualified healthcare professional."
        )
